# Generated by Django 5.0.4 on 2025-11-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeightTicketTable',
            new_name='WeightTicketModel',
        ),
    ]
