    # Generated by Django 5.0.4 on 2025-11-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siipe', '0002_rename_weighttickettable_weightticketmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightticketmodel',
            name='movement_description',
        ),
        migrations.AddField(
            model_name='weightticketmodel',
            name='driver_id',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre del origen o proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weightticketmodel',
            name='provider_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Provedor'),
        ),
        migrations.AddField(
            model_name='weightticketmodel',
            name='provider_tax_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NIT Provedor'),
        ),
        migrations.AlterField(
            model_name='weightticketmodel',
            name='driver_name',
            field=models.CharField(max_length=100, verbose_name='Conductor'),
        ),
    ]
