# Generated by Django 5.0.4 on 2025-11-24 09:58

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeightTicketTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='Tiquete')),
                ('weighing_date', models.DateTimeField(verbose_name='Fecha de pesaje')),
                ('movement_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción del movimiento')),
                ('vehicle_id', models.CharField(max_length=20, verbose_name='Vehículo')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Nombre del origen o proveedor')),
                ('gross_weight_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Bruto (Kg)')),
                ('tare_weight_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Tara (Kg)')),
                ('net_weight_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Neto (Kg)')),
                ('peduncle_long_units', models.IntegerField(blank=True, null=True, verbose_name='Pedúnculo Largo (Unidades)')),
                ('peduncle_long_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kilos Pedúnculo Largo (KPL)')),
                ('sick_bunches_units', models.IntegerField(blank=True, null=True, verbose_name='Racimos Enfermos (Unidades)')),
                ('impurities_units', models.IntegerField(blank=True, null=True, verbose_name='Impurezas (Unidades)')),
                ('impurities_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kilos Impurezas (KI)')),
                ('rotten_fruit_units', models.IntegerField(blank=True, null=True, verbose_name='Fruta Podrida (Unidades)')),
                ('rotten_fruit_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kilos Fruta Podrida (KRP)')),
                ('overripe_fruit_units', models.IntegerField(blank=True, null=True, verbose_name='Fruta Sobremadura (Unidades)')),
                ('overripe_fruit_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kilos Fruta Sobremadura (KRSM)')),
                ('green_fruit_units', models.IntegerField(blank=True, null=True, verbose_name='Fruta Verde (Unidades)')),
                ('green_fruit_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kilos Fruta Verde (KRV)')),
                ('empty_bunches_units', models.IntegerField(blank=True, null=True, verbose_name='Tusas (Unidades)')),
                ('empty_bunches_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kilos Tusas (KT)')),
                ('green_with_detachment_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Verde con Desprendimiento (Kg)')),
                ('penalty_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Castigo (Kg)')),
                ('payable_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='A Pagar (Kg)')),
            ],
            options={
                'verbose_name': 'weight ticket',
                'verbose_name_plural': 'weight tickets',
                'ordering': ['-weighing_date'],
            },
        ),
    ]
